services:
  app:
    restart: unless-stopped
    build: .
    env_file:
      - .env
    environment:
      MONGO_URI: mongodb://mongodb:27017
      REDIS_URL: redis://redis:6379/0
    depends_on:
      mongodb:
        condition: service_healthy
      redis:
        condition: service_healthy

  mongodb:
    restart: unless-stopped
    image: mongo:8
    healthcheck:
      test: ["CMD", "mongosh", "--quiet", "--eval", "db.adminCommand('ping').ok"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    volumes:
      - mongodb_data:/data/db
    ports:
      - "27017:27017"

  redis:
    restart: unless-stopped
    image: redis:8
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s

volumes:
  mongodb_data:
